# ============================================================================
# KUBERNETES SERVICES - INTENTIONALLY INSECURE
# ============================================================================
# Exposes SecureBank services
#
# Intentional Violations:
# - LoadBalancer type exposes services to internet
# - No network policies
# - No service mesh
# - HTTP not HTTPS
# ============================================================================

---
# Backend Service - LoadBalancer (Public!)
apiVersion: v1
kind: Service
metadata:
  name: securebank-backend-service
  namespace: securebank
  labels:
    app: securebank
    component: backend
  annotations:
    # ❌ PCI 1.2.1: Public-facing service
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  # ❌ PUBLIC!
spec:
  type: LoadBalancer  # ❌ Exposes to internet!
  selector:
    app: securebank
    component: backend
  ports:
  - name: http
    port: 80  # ❌ HTTP port 80!
    targetPort: 3000
    protocol: TCP
  # ❌ No HTTPS port 443

  # ❌ PCI 1.2.1: Allows traffic from anywhere
  # externalTrafficPolicy: Local

---
# Frontend Service - LoadBalancer (Public!)
apiVersion: v1
kind: Service
metadata:
  name: securebank-frontend-service
  namespace: securebank
  labels:
    app: securebank
    component: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: securebank
    component: frontend
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP

---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: securebank
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: securebank
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379

---
# ============================================================================
# SECURE REFERENCE IMPLEMENTATION (For Learning)
# ============================================================================
#
# apiVersion: v1
# kind: Service
# metadata:
#   name: securebank-backend-secure
#   namespace: securebank
#   annotations:
#     # ✅ Internal load balancer
#     service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
#     service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
# spec:
#   type: ClusterIP  # ✅ Internal only
#   selector:
#     app: securebank
#     component: backend
#   ports:
#   - name: https
#     port: 443  # ✅ HTTPS
#     targetPort: 3000
#     protocol: TCP